create table account (
    id             bigint generated by default as identity primary key,
    name           varchar(255) not null,
    type           varchar(16) not null,
    created_at     timestamp with time zone not null,
    cached_balance numeric(19, 4) not null default 0
);

create table ledger_transaction (
    id              bigint generated by default as identity primary key,
    description     varchar(255) not null,
    occurred_at     timestamp with time zone not null,
    idempotency_key varchar(255),
    constraint uq_transaction_idempotency_key unique (idempotency_key)
);

create table transaction_leg (
    id             bigint generated by default as identity primary key,
    transaction_id bigint not null references ledger_transaction (id),
    account_id     bigint not null references account (id),
    amount         numeric(19, 4) not null,
    direction      varchar(6) not null,
    constraint ck_leg_amount_positive check (amount > 0)
);

create index idx_leg_account on transaction_leg (account_id);
create index idx_leg_transaction on transaction_leg (transaction_id);
